version: '2.4'

volumes:
  db-data:
  files:

services:
  php:
    build:
      context: .
      dockerfile: tools/docker/images/Dockerfile
      target: dev
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s
