x-app: &default-app
  env_file:
    - .env

services:
  php:
    <<: *default-app
    build:
      context: .
      target: dev
    volumes:
      - ./:/var/www/html
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default
      - web
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.test-driven-drupal.rule=Host(`test-driven-drupal.docker.localhost`)"

  mysql:
    <<: *default-app
    image: mariadb:10
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s
    networks:
      - default
    labels:
      - "traefik.enable=false"

volumes:
  db-data: {}
  files: {}

networks:
  web:
    name: traefik_proxy
