#!/bin/bash

set -e

TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

DC="${DC:-exec}"

function bash {
  cmd bash "${@}"
}

function ci:test {
  cp .env.example .env

  docker-compose up --detach

  composer validate --strict
  composer install

  DC=exec
  test:quality \
    & test:functional --testdox \
    & wait
}

function cmd {
  # Run any command in the php container.
  _dc php "${@}"
}

function composer {
  # Execute Composer commands.
  cmd composer "${@}"
}

function drupal:install {
  # Install Drupal.
  drush site:install -y --account-pass admin123 --site-name "TestConf"

  drupal:files-directory-permissions
}

function drush {
  # Execute Drush commands.
  cmd drush "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

function test:functional {
  . .env

  _fix_public_files_directory_permissions
  _fix_simpletest_directory_permissions

  _run_tests --testsuite functional "${@}"
}

function test:integration {
  # Run integration tests.
  _run_tests --testsuite kernel "${@}"
}

function test:quality {
  # Run quality checks (code linting, static analysis, etc.).
  DC="run --no-deps"
  cmd phpcs
  cmd phpstan
}

function test:unit {
  # Run unit tests.
  _run_tests --testsuite unit "${@}"
}

function _dc {
  docker-compose ${DC} ${TTY} "${@}"
}

function _fix_public_files_directory_permissions {
  # Ensure that the files directory exists and is writable.
  cmd mkdir -p ${DRUPAL_DOCROOT}/sites/default/files
  cmd chown -R ${DOCKER_WEB_USER}:${DOCKER_WEB_USER} ${DRUPAL_DOCROOT}/sites/default/files
}

function _fix_simpletest_directory_permissions {
  # Ensure that the simpletest site directory exists and is writable.
  cmd mkdir -p ${DRUPAL_DOCROOT}/sites/simpletest
  cmd chown -R ${DOCKER_WEB_USER}:${DOCKER_WEB_USER} ${DRUPAL_DOCROOT}/sites/simpletest
}

function _run_tests {
  . .env

  _dc --user ${DOCKER_WEB_USER} php phpunit "${@}"
}

eval "${@:-help}"
