#!/usr/bin/env bash

set -e

TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

DC="${DC:-exec}"

function ci:test {
  docker compose version

  cp --no-clobber .env.example .env

  DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker compose build --progress plain

  docker network create traefik_proxy

  docker compose up --detach
  docker compose ps
  docker compose logs

  composer install --quiet --no-progress

  cmd phpunit --testdox --colors=always
}

function cmd {
  # Run any command in the php container.
  _dc php "${@}"
}

function composer {
  # Execute Composer commands.
  cmd composer "${@}"
}

function drupal:install {
  # Install Drupal.
  drush site:install -y --account-pass admin123 --site-name "TestConf"

  drupal:files-directory-permissions
}

function drush {
  # Execute Drush commands.
  cmd drush "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

function lint:dockerfile {
  docker container run --rm -i \
    hadolint/hadolint hadolint \
    --ignore=DL3008 \
    --ignore=DL3059 \
    --ignore=DL3022 \
    "${@}" - < Dockerfile
}

function shell {
  cmd bash "${@}"
}

function test {
  . .env

  _dc --user ${DOCKER_WEB_USER} php phpunit "${@}"
}

function test:functional {
  . .env

  _fix_public_files_directory_permissions
  _fix_simpletest_directory_permissions

  test --testsuite functional "${@}"
}

function test:integration {
  # Run integration tests.
  test --testsuite kernel "${@}"
}

function test:quality {
  # Run quality checks (code linting, static analysis, etc.).
  DC="run --no-deps"
  cmd phpcs
  cmd phpstan
}

function test:unit {
  # Run unit tests.
  test --testsuite unit "${@}"
}

function _dc {
  docker compose ${DC} ${TTY} "${@}"
}

function _fix_public_files_directory_permissions {
  # Ensure that the files directory exists and is writable.
  cmd mkdir -p ${DRUPAL_DOCROOT}/sites/default/files
  cmd chown -R ${DOCKER_WEB_USER}:${DOCKER_WEB_USER} ${DRUPAL_DOCROOT}/sites/default/files
}

function _fix_simpletest_directory_permissions {
  # Ensure that the simpletest site directory exists and is writable.
  cmd mkdir -p ${DRUPAL_DOCROOT}/sites/simpletest
  cmd chown -R ${DOCKER_WEB_USER}:${DOCKER_WEB_USER} ${DRUPAL_DOCROOT}/sites/simpletest
}

eval "${@:-help}"
