name: CI

on:
  push:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  test-quality:
    name: Run quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - run: cp .env.example .env
      - run: docker-compose up -d
      - run: ./run composer install
      - run: ./run test:quality

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testsuite:
          - functional
          #- integration
          #- unit
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - run: cp .env.example .env
      - run: docker-compose up -d
      - run: ./run composer install
      - run: ./run test:${{ matrix.testsuite }} --testdox
        env:
          SIMPLETEST_DB: 'mysql://mysql/drupal:drupal/drupal'
