name: CI

on:
  push:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  SIMPLETEST_DB: 'mysql://mysql/drupal:drupal/drupal'

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - run: ./run ci:test
