name: CI

on:
  push:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_PROJECT_NAME: test-driven-drupal-app
  DOCKER_BUILDKIT: 1

jobs:
  tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - run: cp .docker.env.example .docker.env
      - run: make enable
      - run: make test
